>Ирина, приветствую! Меня зовут Кудрявцев Александр и я буду проверять твой проект.
>
>Если ты непротив, мне было бы удобнее общаться на "ты" во время проверки проекта :)
>
>Ниже в ноутбуке будут мои комментарии, закодированные разными цветами.
>
>**<span style="color:green">Зеленым будут выделены места, которые хочется особенно отметить, как хорошие. </span>**
>
>**<span style="color:red">Недочеты, откомментированные красным обязательны к доработке – без их исправления проект не будет зачтен. </span>**
>  
> **<span style="color:orange">Недочеты и подсказки, откомментированные оранжевым, учесть желательно, но их доработка не является обязательным условнием для зачета.</span>**
>
> Если какие-то подзадачи не откомментированны – значит с ними все окей, нет возражений.
>
> Если ошибка влечет за собой дальнейшие неточности рассчетов или выводов – пожалуйста, поправь их тоже, чтобы аналитический отчет был целостным.
>
>Предлагаю быть в диалоге, и, пожалуйста, не удаляй и не переноси мои комментарии, а также выделяй свои новые комментарии цветом (например, синим) — это позволит лучше ориентироваться при возможных повторных проверках.

>Александр, добрый день! Спасибо большое за такую развернутую и подробную обратную связь :)
>
>**<span style="color:blue">Чтобы тебе было удобнее ориентироваться при повторной проверке, я откомментировала синим то, что  исправила. </span>**

# Исследование надёжности заёмщиков

Заказчик — кредитный отдел банка. Нужно разобраться, влияет ли семейное положение и количество детей клиента на факт погашения кредита в срок. Входные данные от банка — статистика о платёжеспособности клиентов.

Результаты исследования будут учтены при построении модели **кредитного скоринга** — специальной системы, которая оценивает способность потенциального заёмщика вернуть кредит банку.

## Шаг 1. Откройте файл с данными и изучите общую информацию

In [126]:
import pandas as pd #импорт библиотеки pandas
data = pd.read_csv('/datasets/data.csv') #чтение файла с данными с сохранением в data
data.info() #получение общей информации о данных в таблице data
data.head(15) #получение информации о первых 15 строках в таблице

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21525 entries, 0 to 21524
Data columns (total 12 columns):
children            21525 non-null int64
days_employed       19351 non-null float64
dob_years           21525 non-null int64
education           21525 non-null object
education_id        21525 non-null int64
family_status       21525 non-null object
family_status_id    21525 non-null int64
gender              21525 non-null object
income_type         21525 non-null object
debt                21525 non-null int64
total_income        19351 non-null float64
purpose             21525 non-null object
dtypes: float64(2), int64(5), object(5)
memory usage: 2.0+ MB

,children,days_employed,dob_years,education,education_id,family_status,family_status_id,gender,income_type,debt,total_income,purpose
0,1,-8437.673028,42,высшее,0,женат / замужем,0,F,сотрудник,0,253875.639453,покупка жилья
1,1,-4024.803754,36,среднее,1,женат / замужем,0,F,сотрудник,0,112080.014102,приобретение автомобиля
2,0,-5623.422610,33,Среднее,1,женат / замужем,0,M,сотрудник,0,145885.952297,покупка жилья
3,3,-4124.747207,32,среднее,1,женат / замужем,0,M,сотрудник,0,267628.550329,дополнительное образование
4,0,340266.072047,53,среднее,1,гражданский брак,1,F,пенсионер,0,158616.077870,сыграть свадьбу
5,0,-926.185831,27,высшее,0,гражданский брак,1,M,компаньон,0,255763.565419,покупка жилья
6,0,-2879.202052,43,высшее,0,женат / замужем,0,F,компаньон,0,240525.971920,операции с жильем
7,0,-152.779569,50,СРЕДНЕЕ,1,женат / замужем,0,M,сотрудник,0,135823.934197,образование
8,2,-6929.865299,35,ВЫСШЕЕ,0,гражданский брак,1,F,сотрудник,0,95856.832424,на проведение свадьбы
9,0,-2188.756445,41,среднее,1,женат / замужем,0,M,сотрудник,0,144425.938277,покупка жилья для семьи
10,2,-4171.483647,36,высшее,0,женат / замужем,0,M,компаньон,0,113943.491460,покупка недвижимости
11,0,-792.701887,40,среднее,1,женат / замужем,0,F,сотрудник,0,77069.234271,покупка коммерческой недвижимости
12,0,NaN,65,среднее,1,гражданский брак,1,M,пенсионер,0,NaN,сыграть свадьбу
13,0,-1846.641941,54,неоконченное высшее,2,женат / замужем,0,F,сотрудник,0,130458.228857,приобретение автомобиля
14,0,-1844.956182,56,высшее,0,гражданский брак,1,F,компаньон,1,165127.911772,покупка жилой недвижимости

**Вывод**

Рассмотрим полученную информацию подробнее. 

Всего в таблице 12 столбцов. У 12 из них тип - object, у 5 столбцоы тип int64, еще у 2 - float64.

Подробно разберём, какие в *data* столбцы и какую информацию они содержат:
  
* children — количество детей в семье;
* days_employed — общий трудовой стаж в днях;
* dob_years — возраст клиента в годах;
* education — уровень образования клиента;
* education_id — идентификатор уровня образования;
* family_status — семейное положение;
* family_status_id — идентификатор семейного положения;
* gender — пол клиента;
* income_type — тип занятости;
* debt — имел ли задолженность по возврату кредитов;
* total_income — ежемесячный доход;
* purpose — цель получения кредита.

Количество наблюдений в столбцах различается. Это говорит о том, что в данных есть пропущенные значения.

Значения трудового стажа (в днях) не могут быть отрицательными (столбец *days_employed*).

В столбце *education* значения записаны разными регистрами. 

Данные о доходах записаны в дробных числах. Для удобства их  следует перевести в целочисленные значения путем замены типа данных (с float на int). 

В столбце *purpose* одинаковые по смыслу цели (например, "приобретение жилья") отображаются по-разному ("покупка жилой недвижимости", "покупка недвижимости", "покупка жилья", "покупка жилья для семьи").

Таким образом, выявлены основные проблемы, требующие решения: пропущенные значения, некорректный тип данных, некачественные значения в столбцах.

>**<span style="color:green">Здесь всё структурировано и по делу, класс. </span>**
>

## Шаг 2. Предобработка данных

### Обработка пропусков

In [127]:
print(data.isnull().sum()) #подсчет отсутствуюищх значений в каждом столбце

children               0
days_employed       2174
dob_years              0
education              0
education_id           0
family_status          0
family_status_id       0
gender                 0
income_type            0
debt                   0
total_income        2174
purpose                0
dtype: int64

In [128]:
print(data['days_employed'].min()/365) #определяем минимальное значение трудового стажа и для наглядности переводим полученное значение в годы

-50.38068465909146

In [129]:
print(data['days_employed'].max()/365)#определяем максимальное значение трудового стажа и для наглядности переводим полученное значение в годы

1100.6997273296713

>**<span style="color:green">Скорее всего в этих данных есть аномалия, и для некоторых типов занятости данные указаны с минусом и в другой временной шкале. </span>**

In [130]:
print('Среднее значение:', data['days_employed'].mean()/365) #находим среднее
print('Медиана:', data['days_employed'].median()/365) #находим медиану
data['days_employed'] = data['days_employed'].fillna(0) #замена пропущенных переменных на нули

Среднее значение: 172.73013057937914
Медиана: -3.296902818549285

In [131]:
print(len(data['income_type'].unique())) #определяем сколько уникальных  типов занятости

8

In [132]:
print(data['income_type'].value_counts())#определяем какие именно типы занятости встречаются и сколько раз

сотрудник          11119
компаньон           5085
пенсионер           3856
госслужащий         1459
безработный            2
предприниматель        2
студент                1
в декрете              1
Name: income_type, dtype: int64

In [133]:
print(data[['income_type','total_income']].groupby('income_type').mean().sort_values('total_income',ascending=False))#находим среднее значение дохода для каждого типа занятости

                  total_income
income_type
предприниматель  499163.144947
компаньон        202417.461462
госслужащий      170898.309923
сотрудник        161380.260488
пенсионер        137127.465690
безработный      131339.751676
студент           98201.625314
в декрете         53829.130729

In [134]:
print(data[['income_type','total_income']].groupby('income_type').median().sort_values('total_income',ascending=False))#находим медианное значение дохода для каждого типа занятости

                  total_income
income_type
предприниматель  499163.144947
компаньон        172357.950966
госслужащий      150447.935283
сотрудник        142594.396847
безработный      131339.751676
пенсионер        118514.486412
студент           98201.625314
в декрете         53829.130729

In [135]:
data['total_income']=data['total_income'].fillna(data.groupby('income_type')['total_income'].transform('median')) #замена пропущенных значений по категориям на медианную заработную плату

In [136]:
print(data.isnull().sum()) #подсчет отсутствуюищх значений в каждом столбце после замены

children            0
days_employed       0
dob_years           0
education           0
education_id        0
family_status       0
family_status_id    0
gender              0
income_type         0
debt                0
total_income        0
purpose             0
dtype: int64

In [137]:
data.head(15) #получение информации о первых 15 строках в таблице

,children,days_employed,dob_years,education,education_id,family_status,family_status_id,gender,income_type,debt,total_income,purpose
0,1,-8437.673028,42,высшее,0,женат / замужем,0,F,сотрудник,0,253875.639453,покупка жилья
1,1,-4024.803754,36,среднее,1,женат / замужем,0,F,сотрудник,0,112080.014102,приобретение автомобиля
2,0,-5623.422610,33,Среднее,1,женат / замужем,0,M,сотрудник,0,145885.952297,покупка жилья
3,3,-4124.747207,32,среднее,1,женат / замужем,0,M,сотрудник,0,267628.550329,дополнительное образование
4,0,340266.072047,53,среднее,1,гражданский брак,1,F,пенсионер,0,158616.077870,сыграть свадьбу
5,0,-926.185831,27,высшее,0,гражданский брак,1,M,компаньон,0,255763.565419,покупка жилья
6,0,-2879.202052,43,высшее,0,женат / замужем,0,F,компаньон,0,240525.971920,операции с жильем
7,0,-152.779569,50,СРЕДНЕЕ,1,женат / замужем,0,M,сотрудник,0,135823.934197,образование
8,2,-6929.865299,35,ВЫСШЕЕ,0,гражданский брак,1,F,сотрудник,0,95856.832424,на проведение свадьбы
9,0,-2188.756445,41,среднее,1,женат / замужем,0,M,сотрудник,0,144425.938277,покупка жилья для семьи
10,2,-4171.483647,36,высшее,0,женат / замужем,0,M,компаньон,0,113943.491460,покупка недвижимости
11,0,-792.701887,40,среднее,1,женат / замужем,0,F,сотрудник,0,77069.234271,покупка коммерческой недвижимости
12,0,0.000000,65,среднее,1,гражданский брак,1,M,пенсионер,0,118514.486412,сыграть свадьбу
13,0,-1846.641941,54,неоконченное высшее,2,женат / замужем,0,F,сотрудник,0,130458.228857,приобретение автомобиля
14,0,-1844.956182,56,высшее,0,гражданский брак,1,F,компаньон,1,165127.911772,покупка жилой недвижимости

In [138]:
data.info() #получение общей информации о таблице data

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21525 entries, 0 to 21524
Data columns (total 12 columns):
children            21525 non-null int64
days_employed       21525 non-null float64
dob_years           21525 non-null int64
education           21525 non-null object
education_id        21525 non-null int64
family_status       21525 non-null object
family_status_id    21525 non-null int64
gender              21525 non-null object
income_type         21525 non-null object
debt                21525 non-null int64
total_income        21525 non-null float64
purpose             21525 non-null object
dtypes: float64(2), int64(5), object(5)
memory usage: 2.0+ MB

**Вывод**

Пропущенные значения есть в количественных переменных *days_employed* и *total_income*.

Количество пропущенных значений в столбцах составляет около 10% от всего количества наблюдений. В данном случае удаление строк приведет к искажению результатов, поэтому требуется заменить пропущенные значения.

Рассчитано максимальное и минимальное значение трудового стажа в днях и полученные значения переведены в количество лет (путем деления на количество дней в году - 365 дней). Максимально значение равно 1100 лет, а минимальное значение отрицательное - -50 лет. Такого в действительности быть не может, поэтому можно сделать вывод о наличии технического сбоя при записи данных. Медиана и среднее значение получились нереалистичными.Поскольку столбец *days_employed* не требуется для дальнейших расчетов, пропущенные переменные заменяем нулями.

Подробнее рассмотрим столбец *total_income*.
Для начала ознакомимся с типами занятости *income_type*. Всего в столбце 8 уникальных значений типов.
Для каждого типа занятости посчитаем значение среднего и медианного дохода.
Для 4 типов занятости (компаньон, сотрудник, госслужащий, пенсионер) значение медианного дохода ниже среднего. 
Среднее значение доходов, как правило, некорректно характеризует данные, когда некоторые значения в группе сильно выделяются среди большинства. Поэтому логично заменить пропуски в доходах медианным значением в зависимости от типа занятости.

В результате исключения столбца и замены пропусков в доходах получен *data_new* с одинаковым количеством наблюдений в столбцах.

>**<span style="color:green">Отличное решение с заменой пропусков в `total_income` в зависимости от типа занятости клиента и использование функции `transform`. При таком подходе мы получим наиболее приближенное к реальности распределение. Молодец!</span>**

### Замена типа данных

In [139]:
data['total_income']=data['total_income'].astype('int') #замена типа данных столбца total_income с вещественного на целочисленный
data['days_employed']=data['days_employed'].astype('int') #замена типа данных столбца days_employed с вещественного на целочисленный
data.info() #получение общей информации о таблице data
data.head() #получение информации о первых 5 строках таблицы data

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21525 entries, 0 to 21524
Data columns (total 12 columns):
children            21525 non-null int64
days_employed       21525 non-null int64
dob_years           21525 non-null int64
education           21525 non-null object
education_id        21525 non-null int64
family_status       21525 non-null object
family_status_id    21525 non-null int64
gender              21525 non-null object
income_type         21525 non-null object
debt                21525 non-null int64
total_income        21525 non-null int64
purpose             21525 non-null object
dtypes: int64(7), object(5)
memory usage: 2.0+ MB

,children,days_employed,dob_years,education,education_id,family_status,family_status_id,gender,income_type,debt,total_income,purpose
0,1,-8437,42,высшее,0,женат / замужем,0,F,сотрудник,0,253875,покупка жилья
1,1,-4024,36,среднее,1,женат / замужем,0,F,сотрудник,0,112080,приобретение автомобиля
2,0,-5623,33,Среднее,1,женат / замужем,0,M,сотрудник,0,145885,покупка жилья
3,3,-4124,32,среднее,1,женат / замужем,0,M,сотрудник,0,267628,дополнительное образование
4,0,340266,53,среднее,1,гражданский брак,1,F,пенсионер,0,158616,сыграть свадьбу

**Вывод**

Для замены вещественного типа данных на целочисленный использован метод .astype().
Выбор метода обусловлен тем, что данный метод работает без ошибок, когда отсутствуют пропуски в данных.
Замена типа данных столбца days_employed продиктована логикой - количество дней не может быть не целым.
Значения ежемесячного дохода удобнее рассматривать в целых рублях, поскольку при сравнении значения копеек не критичны и от них можно избавиться. Кроме того у финансовых показателей после запятой обычно два знака, а в исходных данных было 6, поэтому было решено перевести в целочисленные значения.

>**<span style="color:green">Здесь все окей, молодец!</span>**

### Обработка дубликатов

In [140]:
data.duplicated().sum() #получение данных о суммарном количестве дубликатов в таблице data

54

In [141]:
data = data.drop_duplicates().reset_index(drop= True)# <удаление всех дубликатов из таблицы data специальным методом>

In [142]:
data.duplicated().sum() #проверка на отсутствие дубликатов

0

In [143]:
print(len(data['education'].unique())) #определяем сколько уникальных значений столбца education

15

In [144]:
print(data['education'].value_counts()) #определяем какие именно и сколько уникальных значений в столбце education

среднее                13705
высшее                  4710
СРЕДНЕЕ                  772
Среднее                  711
неоконченное высшее      668
ВЫСШЕЕ                   273
Высшее                   268
начальное                250
Неоконченное высшее       47
НЕОКОНЧЕННОЕ ВЫСШЕЕ       29
НАЧАЛЬНОЕ                 17
Начальное                 15
ученая степень             4
УЧЕНАЯ СТЕПЕНЬ             1
Ученая степень             1
Name: education, dtype: int64

In [145]:
data['education'] = data['education'].str.lower() # сохраняем столбец education в нижнем регистре
print(data['education'].value_counts()) #делаем проверку правильности замены

среднее                15188
высшее                  5251
неоконченное высшее      744
начальное                282
ученая степень             6
Name: education, dtype: int64

In [146]:
print(len(data['family_status'].unique())) #проверяем количество уникальных значений в столбце family_status
data['family_status'] = data['family_status'].str.lower() #сохраняем столбец в нижнем регистре
print(data['family_status'].value_counts())

5
женат / замужем          12344
гражданский брак          4163
не женат / не замужем     2810
в разводе                 1195
вдовец / вдова             959
Name: family_status, dtype: int64

In [147]:
data.duplicated().sum() #проверка на отсутствие дубликатов

17

In [148]:
data = data.drop_duplicates().reset_index(drop= True)# <удаление всех дубликатов из таблицы data специальным методом>

In [149]:
data.duplicated().sum() #повторная проверка на отсутствие дубликатов

0

In [150]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21454 entries, 0 to 21453
Data columns (total 12 columns):
children            21454 non-null int64
days_employed       21454 non-null int64
dob_years           21454 non-null int64
education           21454 non-null object
education_id        21454 non-null int64
family_status       21454 non-null object
family_status_id    21454 non-null int64
gender              21454 non-null object
income_type         21454 non-null object
debt                21454 non-null int64
total_income        21454 non-null int64
purpose             21454 non-null object
dtypes: int64(7), object(5)
memory usage: 2.0+ MB

**Вывод**

При помощи метода .duplicated() в датафрейме выявлены 54 дубликата. Для того, чтобы не исказить результаты избавимся от дубликатов методом .drop_duplicates() с сохранением индекса.

Дубликаты могли появиться вследствие сбоя в записи данных. Проверим наличие неявных дубликатов.

В столбце education значения записаны в разных регистрах. Поиск уникальных значений выявил 15 различных по написанию значений, но среди них встречаются одинаковые по смыслу. Столбец был сохранен в нижнем регистре. После преобразований выявлено 5 уникальных значений.

В столбце family_status выявлены значения "Не женат / не замужем". Столбец также был сохранен в нижнем регистре.

После преобразований были выявлены еще 17 дубликатов. Они также были удалены методом .drop_duplicates() с сохранением индекса.

>**<span style="color:green">Круто что ты обнаружила разницу в регистре в колонке с образованием, теперь мы смогли найти все полные дубликаты строк. </span>**

### Лемматизация

In [151]:
from pymystem3 import Mystem #импорт библиотеки Mystem
m = Mystem() #импорт библиотеки Mystem

In [152]:
print(len(data['purpose'].unique())) #подсчет количества уникальных значений
print(data['purpose'].unique()) #вывод на экран список уникальных значений столбца purpose

38
['покупка жилья' 'приобретение автомобиля' 'дополнительное образование'
 'сыграть свадьбу' 'операции с жильем' 'образование'
 'на проведение свадьбы' 'покупка жилья для семьи' 'покупка недвижимости'
 'покупка коммерческой недвижимости' 'покупка жилой недвижимости'
 'строительство собственной недвижимости' 'недвижимость'
 'строительство недвижимости' 'на покупку подержанного автомобиля'
 'на покупку своего автомобиля' 'операции с коммерческой недвижимостью'
 'строительство жилой недвижимости' 'жилье'
 'операции со своей недвижимостью' 'автомобили' 'заняться образованием'
 'сделка с подержанным автомобилем' 'получение образования' 'автомобиль'
 'свадьба' 'получение дополнительного образования' 'покупка своего жилья'
 'операции с недвижимостью' 'получение высшего образования'
 'свой автомобиль' 'сделка с автомобилем' 'профильное образование'
 'высшее образование' 'покупка жилья для сдачи' 'на покупку автомобиля'
 'ремонт жилью' 'заняться высшим образованием']

In [153]:
def create_category_purpose(row):
    lem_purpose = m.lemmatize(row['purpose'])
    if 'жилье' in lem_purpose: #выделяем леммы в столбце purpose
        return 'недвижимость'
    if 'автомобиль' in lem_purpose:
        return 'автомобиль'
    if 'образование' in lem_purpose:
        return 'образование'
    if 'недвижимость' in lem_purpose:
        return 'недвижимость'
    if 'свадьба' in lem_purpose:
        return 'свадьба'
    return 'прочие цели'

data['purpose'] = data.apply(create_category_purpose, axis=1) #заменяем значения столбца purpose лемматизированными значениями

In [154]:
data.head(10)

,children,days_employed,dob_years,education,education_id,family_status,family_status_id,gender,income_type,debt,total_income,purpose
0,1,-8437,42,высшее,0,женат / замужем,0,F,сотрудник,0,253875,недвижимость
1,1,-4024,36,среднее,1,женат / замужем,0,F,сотрудник,0,112080,автомобиль
2,0,-5623,33,среднее,1,женат / замужем,0,M,сотрудник,0,145885,недвижимость
3,3,-4124,32,среднее,1,женат / замужем,0,M,сотрудник,0,267628,образование
4,0,340266,53,среднее,1,гражданский брак,1,F,пенсионер,0,158616,свадьба
5,0,-926,27,высшее,0,гражданский брак,1,M,компаньон,0,255763,недвижимость
6,0,-2879,43,высшее,0,женат / замужем,0,F,компаньон,0,240525,недвижимость
7,0,-152,50,среднее,1,женат / замужем,0,M,сотрудник,0,135823,образование
8,2,-6929,35,высшее,0,гражданский брак,1,F,сотрудник,0,95856,свадьба
9,0,-2188,41,среднее,1,женат / замужем,0,M,сотрудник,0,144425,недвижимость

In [155]:
print(data['purpose'].unique()) #подсчет количества уникальных значений для проверки

['недвижимость' 'автомобиль' 'образование' 'свадьба']

In [156]:
data.info() #проверка правильности

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21454 entries, 0 to 21453
Data columns (total 12 columns):
children            21454 non-null int64
days_employed       21454 non-null int64
dob_years           21454 non-null int64
education           21454 non-null object
education_id        21454 non-null int64
family_status       21454 non-null object
family_status_id    21454 non-null int64
gender              21454 non-null object
income_type         21454 non-null object
debt                21454 non-null int64
total_income        21454 non-null int64
purpose             21454 non-null object
dtypes: int64(7), object(5)
memory usage: 2.0+ MB

**Вывод**

В столбце purpose встречаются значения одинаковые по смыслу, но отличающиеся написанием. Всего таких "уникальных" значений 38.
Для начала были определены какие именно значения присутствуют в столбце purpose. 

Среди них можно выделить 4 больших категории целей получения кредита: 'недвижимость/жилье', 'автомобиль', 'образование', 'свадьба'. 
Для решения поставленной задачи данные были раскиданы по этим четырем категориям. Для этого использована функция, в теле которой записаны условия для распределения значений столбца purpose в зависимости от леммы.
С использованием метода .apply() исходные значения были заменены значениями-результатами работы функции.
В результате повторного вызова метода .unique() получены 4 уникальных значения. Функция работает корректно.

>**<span style="color:green">С лемматизацией у тебя тоже полный порядок. В качестве небольшого дополнения мы могли бы еще посчитать общую частотность и встречаемость слов в нашем датасете - это сократит шанс упустить важную категорию (в нашем случае все более менее очевидно). Чтобы посчитать частотность, можно "склеить" всю колонку с целями в одну большую строку методом `join`, после этого передать эту строку в лемматизатор и применить счётчик `Counter`.</span>**

### Категоризация данных

In [157]:
data['children'].value_counts() #определяем численность изначальных категорий

 0     14091
 1      4808
 2      2052
 3       330
 20       76
-1        47
 4        41
 5         9
Name: children, dtype: int64

In [158]:
data['children'] = data['children'].replace(-1,1) #замена отрицательных значений
data['children'] = data['children'].replace(20,2) #замена слишком больших нереалистичных значений

>**<span style="color:green">Круто, что нашла и поправила аномалии в столбце с детьми.</span>**

In [159]:
data['children'].value_counts() #проверка какие значения в столбце children и сколько раз встречаются

0    14091
1     4855
2     2128
3      330
4       41
5        9
Name: children, dtype: int64

In [160]:
def children_grouped(children): #функция, которая оценивает количество детей и распределяет по категориям 
    
    if children == 0: 
        return 'Бездетный'
    if children >= 1 and children <= 2: 
        return 'Есть дети'
    return 'Многодетный'

data['children_grouped'] = data['children'].apply(children_grouped) #добавление нового стоблца в датафрейм
print(data['children_grouped'].value_counts()) #определяем численность новых категорий

Бездетный      14091
Есть дети       6983
Многодетный      380
Name: children_grouped, dtype: int64

In [161]:
data['income_type'].value_counts() #определяем численность изначальных категорий#определяем численность изначальных категорий

сотрудник          11084
компаньон           5078
пенсионер           3829
госслужащий         1457
безработный            2
предприниматель        2
студент                1
в декрете              1
Name: income_type, dtype: int64

In [162]:
def income_grouped(income_type): #функция, которая оценивает принадлежность к определенной категории доходов
    
    if income_type == 'предприниматель' or income_type =='компаньон':     
        return 'Высокий доход'
    
    if income_type == 'госслужащий' or income_type =='сотрудник':  
        return 'Средний доход'
    
    return 'Низкий доход'

data['income_grouped'] = data['income_type'].apply(income_grouped) #добавление нового стоблца в датафрейм
print(data['income_grouped'].value_counts()) #определяем численность новых категорий

Средний доход    12541
Высокий доход     5080
Низкий доход      3833
Name: income_grouped, dtype: int64

>**<span style="color:orange">Я бы все же предложил тебе определять категорию доходов не из типа занятости, а из реально располагаемых доходов. В нашем случае для определения границ можно использовать квантили (вы будете проходить их чуть позже). Они делят наше распределение на равные "кусочки", например, 50%-ый квантиль == медиане, то есть у нас есть 50% наблюдений с меньшим доходом чем эта сумма, и 50% клиентов у кого больше.</span>**

In [163]:
### Код ревьювера ###

data['total_income'].quantile([0.25, 0.5, 0.75]) #50%-ый квантиль == медиане

0.25    107623.00
0.50    142594.00
0.75    195820.25
Name: total_income, dtype: float64

In [164]:
print(data['family_status'].value_counts()) #определяем численность изначальных категорий
print(data['family_status_id'].value_counts()) #определяем численность изначальных категорий

женат / замужем          12339
гражданский брак          4151
не женат / не замужем     2810
в разводе                 1195
вдовец / вдова             959
Name: family_status, dtype: int64
0    12339
1     4151
4     2810
3     1195
2      959
Name: family_status_id, dtype: int64

In [165]:
def family_status_grouped(family_status): #функция, которая оценивает принадлежность к определенной категории семейного статуса
    
    if family_status == 'женат / замужем': 
            return 'В браке'
    
    if family_status == 'гражданский брак': 
            return 'В отношениях'
    
    return 'Одинокий'

data['family_status_grouped'] = data['family_status'].apply(family_status_grouped)

print(data['family_status_grouped'].value_counts()) #определяем численность новых категорий

В браке         12339
Одинокий         4964
В отношениях     4151
Name: family_status_grouped, dtype: int64

**Вывод**

Для того, чтобы корректно ответить на основные вопросы проекта, необходимо категоризировать столбцы с данными о количестве детей, уровне доходов и семейном положении. Работать с единичными отрывками и делать из них статистические выводы нельзя. Значит, нужно сгруппировать данные, чтобы численности каждой группы хватало для формулировки выводов. 

Для начала при помощи метода .value_counts получена информация о количестве значений столбца *children*. Выявлены отрицательные значения (у 47 респондентов -1 ребенок), а также нереалистично высокие и при этом достаточно часто встречающиеся (76 респондентов 20 детей). Указанные значения скорее всего являются результатом некорректного ввдода данных в систему (человеческий фактор или технический сбой), поэтому они были заменены на 1 и 2 при помощи метода .replace(). Затем столбец *children* был категоризирован в зависимости от количества детей, поскольку работать с единичными отрывками и делать из них статистические выводы нельзя:
- нет детей (если значение столбца равно 0),
- есть дети (если значение столбца в диапазоне от 1 до 2),
- многодетный (если значение столбца больше 3).

Столбец *income_type* был категоризирован в зависимости от уровня доходов, поскольку численности каждой группы не хватает для формулировки выводов (единицы предпринимателей, безработных, в декрете и студентов):
- высокий (предприниматель/компаньон),
- средний (сотрудник/госслужащий),
- низкий (безработный/студент/в декрете/пенсионер).

Столбец *family_status* был категоризирован в зависимости от уровня доходов, поскольку численности каждой группы не хватает для формулировки выводов:
- в браке (женат / замужем),
- в отношениях (гражданский брак),
- одинокий (вдовец / вдова, в разводе, не женат / не замужем).
Новая категоризация семейного положения выявила, что количество одиноких людей больше, чем в гражданском браке.

>**<span style="color:green">С категоризацией у тебя полный порядок, можно приступать к анализу ;)</span>**

## Шаг 3. Ответьте на вопросы

- Есть ли зависимость между наличием детей и возвратом кредита в срок?

In [166]:
data_pivot = data.pivot_table(index=['children_grouped'], columns='debt', values='children', aggfunc='count') #сводная таблица
data_pivot['debtor_percantage'] = round(data_pivot[1]/(data_pivot[1]+data_pivot[0]),2) #рассчет метрики
data_pivot.sort_values('debtor_percantage',ascending=False)

debt                  0     1  debtor_percantage
children_grouped
Есть дети          6336   647               0.09
Бездетный         13028  1063               0.08
Многодетный         349    31               0.08

**Вывод**

Для того, чтобы сравнить разные категории людей рассчитана метрика *debtor_percantage*, которая отражает долю людей с задолженностью по возврату кредита внутри каждой категории. Полученное значение было округлено до 2 знаков после запятой. Чем выше значение метрики, тем чаще человек имеет задолженность по возврату кредита.
Среди людей, которые имеют 1-2 детей, таких 9%.
Среди людей, у которых нет детей около 8%.
Среди многодетных - 8%.
Однозначный вывод о наличии зависимости между количеством детей и возвратом кредита в срок сделать сложно, но при оценке платежеспособности стоит обратить внимание на категорию людей, у которых 1-2 ребенка.
>**<span style="color:blue"> Вероятно люди, у которых 1-2 ребенка для банка кажутся более надежными заемщиками, чем родители 3 и более детей. Ведь с увеличением количества детей и при условии неизменности доходов родителей, финансовое положение семьи ухудшается (падает доход семьи на 1 человека). Поэтому банки тщательнее проверяют людей с 3 и более детьми  прежде чем одобрить им кредит. В результате наблюдается ситуация, когда среди людей с 1-2 детьми должников больше, чем среди людей с 3 и более детьми. </span>**

>**<span style="color:red">~~По расчётам и выводам у тебя полный порядок. Но нужно добавить твои гипотезы и предположения относительно возможных причин такой разницы в уровне дефолтности клиентов с разным количеством детей. Для нашего заказчика в лице банка, эта разница достаточно велика и может повлиять на итоговое решение о выдаче кредита, а понимание возможных первопричин позволит банку выстроить качественную скоринговую модель. Добавь, пожалуйста.~~</span>**

>>**<span style="color:green">Update: Все так, а еще скорее всего многодетные семьи получают льготы и мат. помощь от государства, в том числе льготные ставки, например, по ипотеке.</span>_**

In [167]:
### Код ревьювера ###

# альтернативный способ посчитать относительную долю невозвратов

data.groupby('children').agg({'debt':['count', 'sum', 'mean']})

           debt
          count   sum      mean
children
0         14091  1063  0.075438
1          4855   445  0.091658
2          2128   202  0.094925
3           330    27  0.081818
4            41     4  0.097561
5             9     0  0.000000

- Есть ли зависимость между семейным положением и возвратом кредита в срок?

In [168]:
data_pivot = data.pivot_table(index=['family_status_grouped'], columns='debt', values='family_status', aggfunc='count')
data_pivot['debtor_percantage'] = round(data_pivot[1]/(data_pivot[1]+data_pivot[0]),2)
data_pivot.sort_values('debtor_percantage',ascending=False)

debt                       0    1  debtor_percantage
family_status_grouped
В отношениях            3763  388               0.09
Одинокий                4542  422               0.09
В браке                11408  931               0.08

**Вывод**

Для того, чтобы сравнить разные категории людей рассчитана метрика *debtor_percantage*, которая отражает долю людей с задолженностью по возврату кредита внутри каждой категории. Полученное значение было округлено до 2 знаков после запятой. Чем выше значение метрики, тем чаще человек имеет задолженность по возврату кредита.
Среди людей, которые состоят в отношениях должников 9%.
Среди одиноких - 9%.
Среди людей, которые состоят в браке должников 8%.
Однозначный вывод о наличии зависимости между семейным положением и возвратом кредита в срок сделать сложно, но при оценке платежеспособности стоит обратить  внимание на людей, состоящих в отношениях и одиночек.
>**<span style="color:blue">Основной причиной почему люди в браке люди реже становятся должниками может быть наличие общего бюджета в семье. Иными словами, когда человек попадает в ситуацию, когда ему буквально нечем платить (например, продолжительная болезнь или увольнение/сокращение), его партнер может помочь ему в выплате кредита. В случае гражданского брака общий бюджет редкость, и в результате обязательтства по выплате долга полностью ложатся заемщика. То же касается и одиночек. При этом для банка женатые/замужние люди выглядят благонадежнее - в представленных данных их почти в 3 раза больше чем людей других категорий.</span>**

>>**<span style="color:green">Update: Отличная и правдивая гипотеза. Скорее всего здесь еще есть прямая взаимосвязь с возрастом заёмщика: чем старше клиент, тем он более ответственно подходит к взятым на себя обязательствам (и, как правило, располагает более стабильным и высоким уровнем доходов); и тем более вероятно, что такой клиент уже состоит/состоял в официальном браке.</span>_**

- Есть ли зависимость между уровнем дохода и возвратом кредита в срок?

In [169]:
data_pivot = data.pivot_table(index=['income_grouped'], columns='debt', values='income_type', aggfunc='count')
data_pivot['debtor_percantage'] = round(data_pivot[1]/(data_pivot[1]+data_pivot[0]),2)
data_pivot.sort_values('debtor_percantage',ascending=False)

debt                0     1  debtor_percantage
income_grouped
Средний доход   11394  1147               0.09
Высокий доход    4704   376               0.07
Низкий доход     3615   218               0.06

**Вывод**

Для того, чтобы сравнить разные категории людей рассчитана метрика *debtor_percantage*, которая отражает долю людей с задолженностью по возврату кредита внутри каждой категории. Полученное значение было округлено до 2 знаков после запятой. Чем выше значение метрики, тем чаще человек имеет задолженность по возврату кредита.
Среди людей со средними ежемесячными доходами (госслужащие и сотрудники) должников 9%.
Среди обеспеченных - 7%.
Среди людей с низкими ежемесячными доходами 6%.
При оценке платежеспособности заемщиков стоит обратить внимание, что среди госслужащих и сотрудников доля людей с задолженностью самая высокая (9%).
>**<span style="color:blue"> Люди со средними доходами самое экономически активное население. Эта категория людей поддерживает спрос в экономике. Для банка такие заемщики выглядят надежнее остальных категорий (в датафрейме заемщиков из этой категории в 3 раза больше, чем из категорий с высокими и низкими доходами). К группе людей со средними доходами я отнесла госслужащих и сотрудников. Если первая группая достаточно стабильная, то представители группы сотрудников как правило чаще меняют работу. При этом, не всегда смена работы означает рост заработной платы. Например, при смены сферы, люди попадают на начальные позиции с более низкими доходами, а долговая нагрузка увеличивается. В результате такие люди становятся должниками. </span>**

- Как разные цели кредита влияют на его возврат в срок?

In [170]:
data_pivot = data.pivot_table(index=['purpose'], columns='debt', values='income_type', aggfunc='count')
data_pivot['debtor_percantage'] = round(data_pivot[1]/(data_pivot[1]+data_pivot[0]),2)
data_pivot.sort_values('debtor_percantage',ascending=False)

debt              0    1  debtor_percantage
purpose
автомобиль     3903  403               0.09
образование    3643  370               0.09
свадьба        2138  186               0.08
недвижимость  10029  782               0.07

**Вывод**

Для того, чтобы сравнить разные категории людей рассчитана метрика *debtor_percantage*, которая отражает долю людей с задолженностью по возврату кредита внутри каждой категории. Полученное значение было округлено до 2 знаков после запятой. Чем выше значение метрики, тем чаще человек имеет задолженность по возврату кредита.
Люди, которые берут кредит для покупки автомобиля и на образование в равной степени становятся должниками (9% должников внутри категорий).
Среди тех, кто берет кредит на свадьбу - 8%.
Среди людей с кредитом на приобретение недвижимости - 7%.
>**<span style="color:blue">Как правило для приобретения жилья оформляют ипотеку. Ипотека оказывается выгоднее кредита - ставка ниже, сроки и сумма кредита больше, а обязательный ежемесячный платеж меньше. Вдобавок при возникновении сложной жизненной стуации возможно оформить ипотечные каникулы, и тем самым избежать задолженности. Поэтому у данной категории людей реже возникают задолженности по возврату кредита.</span>**

>**<span style="color:red">~~По этим пунктам аналогично: давай, пожалуйста, попробуем проработать возможные гипотезы таких расхождений в уровне просроченной задолженности для разных категорий заёмщиков. Умение строить и выдвигать гипотезы — один из ключевых навыков в работе аналитика. Не стесняйся, пожалуйста, отрабатывать этот навык в рамках своих проектов ;)~~</span>**

>>**<span style="color:green">Update: Все круто, молодец!</span>**

## Шаг 4. Общий вывод

- Однозначный вывод о наличии зависимости между количеством детей и возвратом кредита в срок сделать трудно, но при оценке платежеспособности стоит обратить внимание, что люди с 1-2 детьм реже возвращают кредит в срок.
- Среди женатых/замужних людей должников меньше.
- При оценке платежеспособности заемщиков стоит обратить внимание, что среди людей с низкими доходами меньше людей с задолженностью.
- Люди, которые берут кредит для покупки недвижимости реже становятся должниками (7% должников внутри категории).

>**Спасибо тебе за сдачу твоего проекта. Работа получилась просто замечательная и хорошо структурированная. Видно, что ты отлично справилась с материалами спринта и уверенно применяешь полученные навыки на практике. Для зачёта проекта тебе осталось совсем чуть-чуть поработать и исправить ряд некритичных недочётов.**
>
>**Отдельно хочу тебя похвалить за твой комплексный подход к оформлению проекта, твой чистый код и развернутые выводы и комментарии. Продолжай и дальше совершенствоваться в этих аспектах в своих последующих проектах.**
>
>**Буду ждать твой доделанный проект на повторную проверку. Успехов!**


>>**Update: Привет еще раз! Спасибо тебе за оперативную и качественную работу по устранению недочётов. Теперь все точно отлично, и твой проект зачтен. Поздравляю! ;)**

## Чек-лист готовности проекта

Поставьте 'x' в выполненных пунктах. Далее нажмите Shift+Enter.

- [x]  открыт файл;
- [x]  файл изучен;
- [x]  определены пропущенные значения;
- [x]  заполнены пропущенные значения;
- [x]  есть пояснение, какие пропущенные значения обнаружены;
- [x]  описаны возможные причины появления пропусков в данных;
- [x]  объяснено, по какому принципу заполнены пропуски;
- [x]  заменен вещественный тип данных на целочисленный;
- [x]  есть пояснение, какой метод используется для изменения типа данных и почему;
- [x]  удалены дубликаты;
- [x]  есть пояснение, какой метод используется для поиска и удаления дубликатов;
- [x]  описаны возможные причины появления дубликатов в данных;
- [x]  выделены леммы в значениях столбца с целями получения кредита;
- [x]  описан процесс лемматизации;
- [x]  данные категоризированы;
- [x]  есть объяснение принципа категоризации данных;
- [x]  есть ответ на вопрос: "Есть ли зависимость между наличием детей и возвратом кредита в срок?";
- [x]  есть ответ на вопрос: "Есть ли зависимость между семейным положением и возвратом кредита в срок?";
- [x]  есть ответ на вопрос: "Есть ли зависимость между уровнем дохода и возвратом кредита в срок?";
- [x]  есть ответ на вопрос: "Как разные цели кредита влияют на его возврат в срок?";
- [x]  в каждом этапе есть выводы;
- [x]  есть общий вывод.